// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhfO0t9sJ78XsMZV_vN3u4DSkUjw6TuKs',
    appId: '1:142893563437:web:f673c697460c648e1cc2a4',
    messagingSenderId: '142893563437',
    projectId: 'ledgerlite-app',
    authDomain: 'ledgerlite-app.firebaseapp.com',
    storageBucket: 'ledgerlite-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP2ZFBwBAJtv41-ifTZ34icb5G9jJrXws',
    appId: '1:142893563437:android:e66ffed3510e91cc1cc2a4',
    messagingSenderId: '142893563437',
    projectId: 'ledgerlite-app',
    storageBucket: 'ledgerlite-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA64Z6QAEQjeuOSnkEGhsTn-zEKIqEW5Ww',
    appId: '1:142893563437:ios:c256c80ab3e5b3c51cc2a4',
    messagingSenderId: '142893563437',
    projectId: 'ledgerlite-app',
    storageBucket: 'ledgerlite-app.firebasestorage.app',
    iosBundleId: 'com.example.ledgerlite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA64Z6QAEQjeuOSnkEGhsTn-zEKIqEW5Ww',
    appId: '1:142893563437:ios:c256c80ab3e5b3c51cc2a4',
    messagingSenderId: '142893563437',
    projectId: 'ledgerlite-app',
    storageBucket: 'ledgerlite-app.firebasestorage.app',
    iosBundleId: 'com.example.ledgerlite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhfO0t9sJ78XsMZV_vN3u4DSkUjw6TuKs',
    appId: '1:142893563437:web:3938766407cc881c1cc2a4',
    messagingSenderId: '142893563437',
    projectId: 'ledgerlite-app',
    authDomain: 'ledgerlite-app.firebaseapp.com',
    storageBucket: 'ledgerlite-app.firebasestorage.app',
  );
}
