// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6ThfuH33A5hgJlVRNSLpPcX_fusR7Wc0',
    appId: '1:376182475816:web:default',
    messagingSenderId: '376182475816',
    projectId: 'pft-app-aac78',
    authDomain: 'pft-app-aac78.firebaseapp.com',
    storageBucket: 'pft-app-aac78.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6ThfuH33A5hgJlVRNSLpPcX_fusR7Wc0',
    appId: '1:376182475816:android:b6d7d3611b6cbf3cf5b91d',
    messagingSenderId: '376182475816',
    projectId: 'pft-app-aac78',
    storageBucket: 'pft-app-aac78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6ThfuH33A5hgJlVRNSLpPcX_fusR7Wc0',
    appId: '1:376182475816:ios:default',
    messagingSenderId: '376182475816',
    projectId: 'pft-app-aac78',
    storageBucket: 'pft-app-aac78.firebasestorage.app',
    iosBundleId: 'com.pft.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6ThfuH33A5hgJlVRNSLpPcX_fusR7Wc0',
    appId: '1:376182475816:ios:default',
    messagingSenderId: '376182475816',
    projectId: 'pft-app-aac78',
    storageBucket: 'pft-app-aac78.firebasestorage.app',
    iosBundleId: 'com.pft.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6ThfuH33A5hgJlVRNSLpPcX_fusR7Wc0',
    appId: '1:376182475816:web:default',
    messagingSenderId: '376182475816',
    projectId: 'pft-app-aac78',
    authDomain: 'pft-app-aac78.firebaseapp.com',
    storageBucket: 'pft-app-aac78.firebasestorage.app',
  );
}
